import Head from "next/head";
import { Inter } from "next/font/google";
import { ReactElement } from "react";
import AppLayout from "@/components/layout/app-layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3 className="text-green-600 text-xl font-bold">hello world</h3>
    </>
  );
}

Home.getLayout = function (page: ReactElement) {
  return <AppLayout>{page}</AppLayout>;
};
