export const ROUTES = {
  HOME: "/",
  PRODUCT: `/products`,
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms-condition",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/my-account",
  ORDERS: "/my-account/orders",
  ACCOUNT_DETAILS: "/my-account/account-details",
  CHANGE_PASSWORD: "/my-account/change-password",
  SHOPS: "/shops",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  COLLECTIONS: "/collections",
  CATEGORY: "/category",
  ORDER: "/order",
  WALLET:"/my-account/wallet",
  ACCOUNT_ADDRESS:"/my-account/address",
  ACCOUNT_WISH_LIST:"/my-account/wish-list",
  BANK_ACCOUNT_WISH_LIST:"/my-account/bank"
};
